### ISSUE TITLE
Feature Request: Support FLoC interest-cohort Permissions-Policy header

### ISSUE THREAD

**Issue by jimjaeger** [pedro-gbf/permissions-policy#7]
Please provide FLoC interest-cohort Permissions-Policy header: https://github.com/WICG/floc#opting-out-of-computation Thanks.

**Comment by jimjaeger** [comment]
https://github.com/pedro-gbf/permissions-policy/pull/8

**Comment by pedro-gbf** [comment]
Hello, your suggested change and PR were merged and released in the following version:

https://github.com/pedro-gbf/permissions-policy/releases/tag/0.5.0

Thanks for the contribution.
